modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

[[mods]] #mandatory
	modId="nomoresleeping" #mandatory
	version="v1.0" #mandatory
	displayName="No More Sleeping" #mandatory
	description='''Sets time to day instantly after going to sleep in a bed, or disables sleep completely (configurable).''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/NoMoreSleeping"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/no-more-sleeping"
	authors="bl4ckscor3"

[[dependencies.nomoresleeping]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nomoresleeping]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"